// Mock API with Nigerian school data structure
export const api = {
	getSchoolInfo: () =>
		Promise.resolve({
			name: 'CHRIST THE KING COLLEGE',
			address: '12 Education Avenue, Ikeja, Lagos State',
			phone: '08012345678',
			email: 'info@ckcollege.edu.ng',
			motto: 'Knowledge is Power',
			logo: '/school-logo.png',
		}),

	getStudents: () =>
		Promise.resolve([
			{
				id: 1,
				admissionNumber: 'CKC/2023/001',
				name: 'ADEBAYO OLUMIDE SAMUEL',
				class: 'SS 2A',
				term: 'FIRST TERM',
				session: '2024/2025',
				age: 16,
				sex: 'MALE',
				height: '5ft 6in',
				weight: '65kg',
				dateOfBirth: '15th March, 2008',
				totalInClass: 45,
				position: 3,
				attendance: {
					present: 92,
					absent: 8,
					total: 100,
				},
				nextTermBegins: '8th January, 2025',
				subjects: [
					{
						name: 'MATHEMATICS',
						ca1: 18,
						ca2: 20,
						exam: 55,
						total: 93,
						grade: 'A1',
						remark: 'EXCELLENT',
						position: 2,
					},
					{
						name: 'ENGLISH LANGUAGE',
						ca1: 15,
						ca2: 18,
						exam: 48,
						total: 81,
						grade: 'B2',
						remark: 'VERY GOOD',
						position: 5,
					},
					{
						name: 'PHYSICS',
						ca1: 17,
						ca2: 19,
						exam: 52,
						total: 88,
						grade: 'A1',
						remark: 'EXCELLENT',
						position: 1,
					},
					{
						name: 'CHEMISTRY',
						ca1: 16,
						ca2: 17,
						exam: 47,
						total: 80,
						grade: 'B2',
						remark: 'VERY GOOD',
						position: 8,
					},
					{
						name: 'BIOLOGY',
						ca1: 19,
						ca2: 18,
						exam: 50,
						total: 87,
						grade: 'A1',
						remark: 'EXCELLENT',
						position: 3,
					},
					{
						name: 'FURTHER MATHEMATICS',
						ca1: 14,
						ca2: 16,
						exam: 45,
						total: 75,
						grade: 'B3',
						remark: 'GOOD',
						position: 12,
					},
					{
						name: 'GEOGRAPHY',
						ca1: 17,
						ca2: 19,
						exam: 49,
						total: 85,
						grade: 'A1',
						remark: 'EXCELLENT',
						position: 4,
					},
					{
						name: 'ECONOMICS',
						ca1: 15,
						ca2: 17,
						exam: 46,
						total: 78,
						grade: 'B2',
						remark: 'VERY GOOD',
						position: 7,
					},
					{
						name: 'GOVERNMENT',
						ca1: 18,
						ca2: 17,
						exam: 48,
						total: 83,
						grade: 'B2',
						remark: 'VERY GOOD',
						position: 6,
					},
				],
				totalScore: 750,
				average: 83.33,
				classTeacherComment:
					'Olumide is a brilliant and dedicated student. He shows excellent understanding in Science subjects. Keep up the good work!',
				principalComment:
					'An outstanding performance. Continue to maintain this excellent standard.',
				promotionStatus: 'PROMOTED TO SS 3',
			},
			{
				id: 2,
				admissionNumber: 'CKC/2023/089',
				name: 'OGBONNA CHIOMA BLESSING',
				class: 'SS 2A',
				term: 'FIRST TERM',
				session: '2024/2025',
				age: 15,
				sex: 'FEMALE',
				height: '5ft 3in',
				weight: '55kg',
				dateOfBirth: '22nd July, 2009',
				totalInClass: 45,
				position: 1,
				attendance: {
					present: 98,
					absent: 2,
					total: 100,
				},
				nextTermBegins: '8th January, 2025',
				subjects: [
					{
						name: 'MATHEMATICS',
						ca1: 20,
						ca2: 19,
						exam: 58,
						total: 97,
						grade: 'A1',
						remark: 'EXCELLENT',
						position: 1,
					},
					{
						name: 'ENGLISH LANGUAGE',
						ca1: 18,
						ca2: 19,
						exam: 55,
						total: 92,
						grade: 'A1',
						remark: 'EXCELLENT',
						position: 1,
					},
					{
						name: 'PHYSICS',
						ca1: 19,
						ca2: 18,
						exam: 54,
						total: 91,
						grade: 'A1',
						remark: 'EXCELLENT',
						position: 2,
					},
					{
						name: 'CHEMISTRY',
						ca1: 17,
						ca2: 18,
						exam: 53,
						total: 88,
						grade: 'A1',
						remark: 'EXCELLENT',
						position: 3,
					},
					{
						name: 'BIOLOGY',
						ca1: 20,
						ca2: 19,
						exam: 56,
						total: 95,
						grade: 'A1',
						remark: 'EXCELLENT',
						position: 1,
					},
					{
						name: 'FURTHER MATHEMATICS',
						ca1: 16,
						ca2: 17,
						exam: 49,
						total: 82,
						grade: 'B2',
						remark: 'VERY GOOD',
						position: 5,
					},
					{
						name: 'GEOGRAPHY',
						ca1: 18,
						ca2: 20,
						exam: 52,
						total: 90,
						grade: 'A1',
						remark: 'EXCELLENT',
						position: 2,
					},
					{
						name: 'ECONOMICS',
						ca1: 17,
						ca2: 18,
						exam: 50,
						total: 85,
						grade: 'A1',
						remark: 'EXCELLENT',
						position: 3,
					},
					{
						name: 'GOVERNMENT',
						ca1: 19,
						ca2: 18,
						exam: 53,
						total: 90,
						grade: 'A1',
						remark: 'EXCELLENT',
						position: 1,
					},
				],
				totalScore: 810,
				average: 90.0,
				classTeacherComment:
					'Chioma is an exceptional student with outstanding performance across all subjects. She is a role model to her peers.',
				principalComment:
					'Excellent performance! Keep up the outstanding work. You are destined for greatness.',
				promotionStatus: 'PROMOTED TO SS 3',
			},
		]),

	generateReport: (studentId) => Promise.resolve({ success: true }),
};
