/**
 * Centralized pricing config.
 * Only define the term price here.
 */

export const PRICING_DISCOUNT_RATE = 0.15; // 15% discount for buying all 3 terms up front

export const RAW_PLANS = [
  {
    name: "Reports Only",
    subtitle: "Basic reporting for small schools",
    termPrice: 1000,
    minStudents: 1,
    maxStudents: 200,
    color: "border-blue-200 bg-blue-50",
    buttonColor: "bg-blue-600 hover:bg-blue-700",
    popular: false,
    features: [
      "Student Registration & Profiles",
      "Teacher Registration & Profiles",
      "Basic Attendance Tracking",
      "Simple Report Generation",
      "Academic Records Reports",
      "Export to PDF/Excel",
      "Email Support",
      "Single Campus Support",
    ],
    limitations: [
      "No Payment Processing",
      "No SMS Notifications",
      "No Advanced Analytics",
      "No Exam Management",
    ],
  },
  {
    name: "Reports + Payment",
    subtitle: "Reports with payment management",
    termPrice: 1600,
    minStudents: 1,
    maxStudents: 500,
    color: "border-green-200 bg-green-50",
    buttonColor: "bg-green-600 hover:bg-green-700",
    popular: true,
    features: [
      "Everything in Reports Only",
      "Fee Payment Management",
      "Payment Tracking & Reports",
      "Outstanding Fees Alerts",
      "Receipt Generation",
      "Payment History",
      "Financial Reports",
      "Parent Payment Portal",
      "Multiple Payment Methods",
      "Automated Payment Reminders",
    ],
    limitations: [
      "No Advanced Exam Management",
      "No Bulk SMS",
      "Limited Analytics",
    ],
  },
  {
    name: "Complete School",
    subtitle: "Full school management system",
    termPrice: 2000,
    minStudents: 1,
    maxStudents: 1000,
    color: "border-purple-200 bg-purple-50",
    buttonColor: "bg-purple-600 hover:bg-purple-700",
    popular: false,
    features: [
      "Everything in Reports + Payment",
      "Advanced Exam Management",
      "Comprehensive Result Processing",
      "Bulk SMS & Email",
      "Staff Management System",
      "Multi-class Timetabling",
      "Assignment Management",
      "Parent Portal Access",
      "Attendance Analytics",
      "Student Behavior Tracking",
      "Library Management",
      "Inventory Management",
      "Priority Support",
    ],
    limitations: ["No Multi-campus Support", "No API Access"],
  },
  {
    name: "Enterprise",
    subtitle: "Advanced features for large institutions",
    termPrice: 3000,
    minStudents: 100,
    maxStudents: 5000,
    color: "border-orange-200 bg-orange-50",
    buttonColor: "bg-orange-600 hover:bg-orange-700",
    popular: false,
    features: [
      "Everything in Complete School",
      "Multi-campus Management",
      "Advanced Analytics Dashboard",
      "Custom Report Builder",
      "API Access & Integrations",
      "White-label Branding",
      "Advanced Security Features",
      "Automated Backup & Recovery",
      "Custom Workflows",
      "Integration with Banks",
      "Biometric Integration",
      "24/7 Priority Support",
      "Dedicated Account Manager",
      "On-site Training Available",
    ],
    limitations: [],
  },
];
