const presetThemes = [
  {
    id: "default",
    name: "Default Blue",
    primary: "#3B82F6",
    secondary: "#1E40AF",
    accent: "#06B6D4",
    background: "#FFFFFF",
    surface: "#F8FAFC",
    text: "#1E293B",
  },
  {
    id: "forest",
    name: "Forest Green",
    primary: "#059669",
    secondary: "#047857",
    accent: "#10B981",
    background: "#FFFFFF",
    surface: "#F0FDF4",
    text: "#064E3B",
  },
  {
    id: "sunset",
    name: "Sunset Orange",
    primary: "#EA580C",
    secondary: "#C2410C",
    accent: "#F97316",
    background: "#FFFFFF",
    surface: "#FFF7ED",
    text: "#9A3412",
  },
  {
    id: "purple",
    name: "Royal Purple",
    primary: "#7C3AED",
    secondary: "#5B21B6",
    accent: "#8B5CF6",
    background: "#FFFFFF",
    surface: "#FAF5FF",
    text: "#581C87",
  },
  {
    id: "dark",
    name: "Dark Mode",
    primary: "#3B82F6",
    secondary: "#1E40AF",
    accent: "#06B6D4",
    background: "#0F172A",
    surface: "#1E293B",
    text: "#F1F5F9",
  },
];
